CREATE TABLE USUARIOS(
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(500),
    EMAIL VARCHAR(500),
    DATA_NASCIMENTO DATE
);

CREATE TABLE HISTORICO_USUARIOS(
    ID SERIAL PRIMARY KEY,
    DATA_ACESSO DATE,
    USUARIO_ID INTEGER REFERENCES USUARIOS (id)
);